#!/usr/bin/ansible-playbook
---

- name: "Pre tasks in local"
  hosts: 127.0.0.1
  user: "root"
  connection: "local"
  gather_facts: "no"
  pre_tasks:
    - copy:
        src: /etc/ansible/remote_files/passwd/master.passwd.open_access_ubuntu16
        dest: /root/baas/master.passwd.open_access_ubuntu16
      # delegate_to: 127.0.0.1
      #remote_src: yes
        backup: yes
      tags: access

    - copy:
        src: /usr/lib/python2.7/site-packages/ansible/modules/custom_modules/gen_pass.py
        dest: /root/baas/gen_pass.py
      # delegate_to: 127.0.0.1
      #remote_src: yes
        backup: yes
      tags: access

    - name: Creating prod_users password file
      command: /usr/bin/python /root/baas/gen_pass.py
    #delegate_to: 127.0.0.1
      tags: access

    - name: check prod user file exists and not empty
      stat:
        path: /root/baas/prod_users
      register: file_details
    #delegate_to: localhost
      tags: access

- name: Effort to maintain credential of BaaS worker/shell servers
  hosts: baas-workers_grp-balaji
  gather_facts: no
  vars_files:
    - "group_vars/prod-workers"
  tasks:
    - name: including roles
      include_role:
        name: workers
      when: file_details.stat.size != 0


    - name: including roles
      include_role:
        name: common_infra
      when: file_details.stat.size != 0
