#!/usr/bin/ansible-playbook
---

- name: Effort to maintain credential of BaaS worker/shell servers
  hosts: baas-workers_grp-balaji
  gather_facts: "no"
  vars_files:
    - "group_vars/prod-workers"
  tasks:
    - copy:
        src: /etc/ansible/remote_files/passwd/master.passwd.open_access_ubuntu16
        dest: /root/baas/master.passwd.open_access_ubuntu16
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - copy:
        src: /usr/lib/python2.7/site-packages/ansible/modules/custom_modules/gen_pass.py
        dest: /root/baas/gen_pass.py
        backup: yes
      delegate_to: 127.0.0.1
      tags: access

    - name: Creating prod_users password file
      command: /usr/bin/python /root/baas/gen_pass.py
      delegate_to: 127.0.0.1
      tags: access

    - name: check prod user file exists and not empty
      stat:
        path: /root/baas/prod_users
      register: file_details
      delegate_to: 127.0.0.1
      tags: access

    - name: including roles
      include_role:
        name: workers
      when: file_details.stat.size != 0
      register: role_output_1

    - name: including roles
      include_role:
        name: common_infra
      when: file_details.stat.size != 0
      register: role_output_2

    - debug: var=role_output_1.changed


# - name: Effort to maintain credential of BaaS worker/shell servers
#   hosts: baas-shell_grp-balaji
#   gather_facts: no
#   vars_files:
#     - "group_vars/qn-prod-shells"
#   tasks:
#   - name: including roles
#     include_role:
#       name: shell-servers
#     when: role_output_1.changed

#   - name: including roles
#     include_role:
#       name: common_infra
#     when: role_output_2.changed
