#!/usr/bin/ansible-playbook
---
- name: Effort to maintain credential of BaaS worker/shell servers
  hosts: baas-workers_grp-balaji
  become_user: "cloudops"
  gather_facts: yes
  vars_files:
    - "group_vars/prod-workers"

- name: including roles
  include_role:
    name: workers


- name: including roles
  include_role:
    name: common_infra
