#!/usr/bin/ansible-playbook
---

- name: Effort to maintain credential of BaaS worker/shell servers
  hosts: baas-workers_grp-balaji
  become_user: "cloudops"
  gather_facts: yes
  vars_files:
    - "group_vars/prod-workers"

  tasks:
  - copy:
      src: /etc/ansible/remote_files/passwd/master.passwd.open_access_ubuntu16
      dest: /root/baas/
      #delegate_to: localhost
      #remote_src: yes
      backup: yes
    tags: access

  - copy:
      src: /usr/lib/python2.7/site-packages/ansible/modules/custom_modules/gen_pass.py
      dest: /root/baas/
      #delegate_to: localhost
      #remote_src: yes
      backup: yes
    tags: access

  - name: Creating prod_users password file
    command: /usr/bin/python /root/baas/gen_pass.py
    delegate_to: localhost
    tags: access

  - name: check prod user file exists and not empty
    stat:
      path: /root/baas/prod_users
    register: file_details
    delegate_to: localhost
    tags: access

  - name: including roles
    include_role:
      name: workers
    when: file_details.stat.size

  - name: including roles
    include_role:
      name: common_infra
