#!/usr/bin/ansible-playbook
---
- name: Effort to stop docker process
  hosts: contrail-ubm-baas
#  become_user: "_cloudmon"
  gather_facts: yes
  #include_vars: "group_vars/qn-prod-shells"
  vars_files:
    - "group_vars/qn-prod-shells"

  tasks:
  - name: including roles
    include_role:
      name: shell-servers

  - name: including roles
    include_role:
      name: common_infra

  - name: including roles
    include_role:
      name: common_baas
