# NFS related tasks
#
- name: Install NFS packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
     - nfs-common
     - rpcbind
  tags: nfs

- name: Install autofs package
  apt:
    name: autofs
    state: present
  tags: nfs

- name: Start autofs
  service:
    name: autofs
    state: started
  tags: nfs

- name: Install /etc/auto.master, /etc/auto.homes and /etc/autofs
  copy:
    src: files/autofs/
    dest: /etc
    force: yes
  register: autofs_files
  tags:
    - nfs
    - autofs

- name: Restart autofs service
  service:
    name: autofs
    state: restarted
  when: autofs_files is changed
  tags:
    - nfs
    - autofs
