- name: Install NTP
  apt:
    name: ntp
    state: present
  tags: ntp

- name: Configure /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart ntp
  tags: ntp

- name: Be sure ntpd is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
